---
- include_vars: nfs.yml

- include: yumPackages.yml
  when: ansible_distribution == 'CentOS'

- include: aptPackages.yml
  when: ansible_distribution == 'Ubuntu'

- name: install autofs if redhat
  yum: name="autofs" state=installed
  sudo: true
  when: ansible_distribution == 'CentOS'

- name: install autofs if debian
  apt: name="autofs" state=installed
  sudo: true
  when: ansible_distribution == 'Ubuntu'

- name: make /nfs
  file: path="/nfs" state=directory
  sudo: true

- lineinfile: dest=/etc/auto.master line="/- file:/etc/auto.eosc"
  sudo: true

- name: add auto.eosc
  sudo: true
  template:
    src: auto.eosc.j2
    dest: "/etc/auto.eosc"
    owner: root
    group: root
    mode: 0644

- name: bring up autofs 
  sudo: yes
  service: name=autofs  state=restarted
