---
- name: stat
  stat: path={{ dest }}
  register: stat_r
  ignore_errors: yes

#- name: debug1
#  debug: var=stat_r

- name: mv
  command: mv {{ dest }} {{ dest }}_old
  when: stat_r.stat.exists and stat_r.stat.isdir
  sudo: true
  ignore_errors: yes

#- name: stat
#  stat: path={{ dest }}
#  register: stat_r
#  ignore_errors: yes
#- name: debug2
#  debug: var=stat_r

#- name: src
#  debug: var="{{ source }}"

#- name: dest
#  debug: var="{{ dest }}"

- name: link
  file: src={{ source }} dest={{ dest }} state=link
  when: not stat_r.stat.exists
  sudo: true
