- name: "Enable Challenge Response"
  lineinfile:
  args:
    dest: /etc/ssh/sshd_config
    regexp: "ChallengeResponseAuthentication yes"
    line: "ChallengeResponseAuthentication no" 
    backrefs: yes
  sudo: true
  notify: 
  - restart sshd
  - restart ssh

- name: "Enable Challenge Response"
  lineinfile:
  args:
    dest: /etc/ssh/sshd_config
    regexp: "PasswordAuthentication no"
    line: "PasswordAuthentication yes"
    backrefs: yes
  sudo: true
  notify: 
  - restart sshd
  - restart ssh

- name: "Disable Challenge Response"
  lineinfile:
  args:
    dest: /etc/ssh/sshd_config
    regexp: "PasswordAuthentication yes"
    line: "PasswordAuthentication no"
    backrefs: yes
  sudo: true
  notify: 
  - restart sshd
  - restart ssh

